### ISSUE TITLE
output folder should be deleted at the beginning of run to clear old files

### ISSUE THREAD

**Issue by kliu57** [WangGithub0/ConvertTxtToHtml#2]
![issue2_outputfolderBeforeRun](https://github.com/WangGithub0/ConvertTxtToHtml/assets/98062538/21edb2cc-7e4d-4367-a68c-8d28e6168fdb)
![issue2_runCommand](https://github.com/WangGithub0/ConvertTxtToHtml/assets/98062538/c7fa5dad-c202-402e-993e-d99615d15fc4)
![issue2_outputfolderAfterRun](https://github.com/WangGithub0/ConvertTxtToHtml/assets/98062538/a8be7ba0-4d4f-4c58-9de4-5e449a689f77)
See above screenshots - output folder was not deleted at the beginning of the run (as you can see junk files were not deleted)

**Comment by WangGithub0** [comment]
yes, thanks, I've revised.
