### ISSUE TITLE
Program should give error message if an input folder contains no .txt files

### ISSUE THREAD

**Issue by kliu57** [WangGithub0/ConvertTxtToHtml#5]
![issue5_inputFolderContents](https://github.com/WangGithub0/ConvertTxtToHtml/assets/98062538/22301579-df38-4865-aaf6-7263c434fb4b)
![issue5_runCommand](https://github.com/WangGithub0/ConvertTxtToHtml/assets/98062538/b20e81c6-7816-46e8-b14a-d699d5cc7585)
![issue5_outputFolderContents](https://github.com/WangGithub0/ConvertTxtToHtml/assets/98062538/8f7b1098-a81c-451d-aa7e-5d5e967864d0)
See above screenshots. Input folder only has one file which was not a .txt file, thus no output files was produced. However there was no message to alert the user of this. There should always be some kind of message after the program runs.

**Comment by WangGithub0** [comment]
good idea, already add it
