### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by Amnish04** [WangGithub0/ConvertTxtToHtml#6]
Hi,

I would like to add Markdown support to your repository, such that it can also process `.md` files.
For starters, I would be adding feature to detect various levels of heading and generate heading tags like `h1`, `h2` accordingly.
Please let me know if its fine.

Thanks,
Amnish

**Comment by WangGithub0** [comment]
@Amnish04  
Hi Amnish, thank you for your prompt response and for considering the addition of Markdown support to the repository. I truly appreciate your willingness to collaborate. But I had a prior commitment with someone who approached me first on Monday, so I've decided to go with her. Once again, thank you for your understanding, and I look forward to cooperating with you.

**Comment by Amnish04** [comment]
@WangGithub0 No worries. I did not see an issue opened, so didn't know.
